# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/sdup/lab/5/stream_acc_system/stream_acc_system.srcs/sources_1/bd/stream_acc_design/ip/stream_acc_design_processing_system7_0_0/stream_acc_design_processing_system7_0_0.xci
# IP: The module: 'stream_acc_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/sdup/lab/5/stream_acc_system/stream_acc_system.srcs/sources_1/bd/stream_acc_design/ip/stream_acc_design_processing_system7_0_0/stream_acc_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'stream_acc_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/sdup/lab/5/stream_acc_system/stream_acc_system.srcs/sources_1/bd/stream_acc_design/ip/stream_acc_design_processing_system7_0_0/stream_acc_design_processing_system7_0_0.xci
# IP: The module: 'stream_acc_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/sdup/lab/5/stream_acc_system/stream_acc_system.srcs/sources_1/bd/stream_acc_design/ip/stream_acc_design_processing_system7_0_0/stream_acc_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'stream_acc_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
